let
  Source = Excel.Workbook(Web.Contents("https://YOURSHAREPOINT/personal/YOURFOLDER/Documents/Apps/Microsoft Power Query/Uploaded Files/Masked_Invoice_Claims_Extract 7.xlsx"), null, true),
  #"Navigation 1" = Source{[Item = "Invoiced Claims", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"PHCY_CLAIM_ID", type text}, {"FILL_NDC_NBR", type text}, {"SERVICED_DTE", type date}, {"product_service_qlfr_cde", type text}, {"FILL_QTY", type number}, {"INFERRED_FILL_QTY", type number}, {"FILL_DAYS_SUPPLY_QTY", Int64.Type}, {"CLAIM_COUNT_NBR", Int64.Type}, {"RX_NBR", Int64.Type}, {"FILL_PHCY_PROVIDER_ROW_ID", Int64.Type}, {"FILL_MEDCO_DRUG_NBR", Int64.Type}, {"PATIENT_ID", Int64.Type}, {"REQUEST_ID", Int64.Type}, {"CLI_FORM_CDE", type text}, {"CLI_CLASS_CDE", Int64.Type}, {"SERVICE_TYPE_CDE", type text}, {"EXCLUSION_TYPE_CDE", type text}, {"EXCLUSION_NBR", Int64.Type}, {"RPT_DETAIL_ID", Int64.Type}, {"FILL_DRUG_FORMULARY_ID", Int64.Type}, {"FORMULARY_TYPE_CDE", Int64.Type}, {"CPC_ID", Int64.Type}, {"CPC_MFR_FORM_NBR", Int64.Type}, {"CPC_BRAND_FORM_NBR", Int64.Type}, {"SOURCE_DB_IND", type text}, {"TOTAL_REBATE_PCT", type number}, {"TOTAL_REBATE_AMT", type number}, {"BID_ENH_ID", Int64.Type}, {"PRICE_AMT", type number}, {"PRE_PAY_CELL_NBR", Int64.Type}, {"POST_PAY_CELL_NBR", type text}, {"medicaid_ind", type text}, {"TRAN_ID", type text}, {"CLAIM_TRAN_IND", Int64.Type}, {"TOTAL_QTR_REBATE_PCT", Int64.Type}, {"TOTAL_QTR_REBATE_AMT", Int64.Type}, {"CLI_CLASS_COND_NBR", Int64.Type}, {"IP_CLIENT_EXCL_IND", type text}, {"CONTRACT_TYPE_CDE", type text}, {"contract_type_ind", type text}, {"gov_program_ind", type text}, {"global_request_id", Int64.Type}, {"mfr_id", Int64.Type}, {"proper_per_eff_dte", type date}, {"req_type_cde", type text}, {"CLAIM_340B_IND", type text}, {"CARRIER_OPERATIONAL_ID", type text}, {"CONTRACT_OPERATIONAL_ID", type text}, {"GROUP_OPERATIONAL_ID", type text}, {"CLIENT_MEMBERSHIP_ID", type text}, {"BDRO_CATEGORY_ID", type text}, {"BDRO_RULE_ID", type text}})
in
  #"Changed column type"