let
  Source = Table.NestedJoin(#"Get GpkDke", {"Dispute Type"}, #"Get Reason Lookup Master", {"gpkdke key"}, "Get Reason Lookup Master", JoinKind.Inner),
  #"Expanded Get Reason Lookup Master" = Table.ExpandTableColumn(Source, "Get Reason Lookup Master", {"CodeID", "Rank"}, {"CodeID", "Rank"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded Get Reason Lookup Master", {"Client Name", "Client ID", "Client Type", "Provider Name", "Provider State", "Provider XRef ID", "NCPDP ID", "NPI", "Provider Type", "Std Mail Indicator", "Paid Amt", "CoPay Amt", "Bid Enhancement ID", "Client Class Code", "Plan Name", "Rebate Transaction ID", "Benefit Stage Qualifier", "Segment 1", "Rebate Batch Number", "File Name Text", "Payout Cell Number", "Formulary Code", "Invoiced Rebate Rate", "Invoiced Rebate Amt", "Invoice Desc 1", "Invoice Amt 1", "Invoice Desc 2", "Invoice Amt 2", "Invoice Desc 3", "Invoice Amt 3", "Invoice Desc 4", "Invoice Amt 4", "Invoice Desc 5", "Invoice Amt 5", "Maximum Aberrant Amount Allowed", "Amount Aberrant", "Tracking ID", "Diagnosis Code", "Rx Number", "Fill Date", "Brand Name", "NDC", "Days Supply", "Refill Ind", "Claims", "Units", "Calculated Unit Price", "Calculated Sales Amt", "Calculated Rebate % of Sales", "Calculated Rebate Amt", "Total Exclusions", "Dispute Type"}),
  #"Grouped rows" = Table.Group(#"Removed columns", {"Ce Claim No"}, {{"Top Priority", each List.Min([Rank]), type nullable Int64.Type}, {"Top Code", each List.Min([CodeID]), type nullable text}})
in
  #"Grouped rows"