let
  Source = Excel.Workbook(Web.Contents("https://YOURSHAREPOINT.sharepoint.com/personal/YOURUSER/Documents/Apps/Microsoft Power Query/Uploaded Files/Masked_Scrub_File_15 3.xlsx"), null, true),
  #"Navigation 1" = Source{[Item = "GpkDke", Kind = "Sheet"]}[Data],
  #"Removed top rows" = Table.Skip(#"Navigation 1", 8),
  #"Promoted headers" = Table.PromoteHeaders(#"Removed top rows", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Zero Dollar Rebate", Int64.Type}, {"Timeframe - Prior Period Claims", Int64.Type}, {"Product - Package Size", Int64.Type}, {"Product - Non-contract Ndc", Int64.Type}, {"Prior Exclusion Credit", Int64.Type}, {"Total Exclusions", Int64.Type}, {"Pharmacy - Non-standard", Int64.Type}, {"Pharmacy - Location", Int64.Type}, {"Pharmacy - Custom Up Front", Int64.Type}, {"Pharmacy - Custom Fss", Int64.Type}, {"Pharmacy - 340B Covered Entity", Int64.Type}, {"Duplication - Vertical", Int64.Type}, {"Duplication - Medicaid - Horizontal/vertical", Int64.Type}, {"Duplication - Internal", Int64.Type}, {"Duplication - Horizontal/vertical", Int64.Type}, {"Duplication - Horizontal", Int64.Type}, {"Aberrant Quantity - Non-mail", Int64.Type}, {"Aberrant Quantity - Mail", Int64.Type}}),
  #"Unpivoted columns" = Table.UnpivotOtherColumns(#"Changed column type", {"Client Name", "Client ID", "Client Type", "Provider Name", "Provider State", "Provider XRef ID", "NCPDP ID", "NPI", "Provider Type", "Std Mail Indicator", "Paid Amt", "CoPay Amt", "Bid Enhancement ID", "Client Class Code", "Plan Name", "Rebate Transaction ID", "Benefit Stage Qualifier ", "Segment 1", "Rebate Batch Number", "File Name Text", "Payout Cell Number", "Formulary Code", "Invoiced Rebate Rate", "Invoiced Rebate Amt", "Invoice Desc 1", "Invoice Amt 1", "Invoice Desc 2", "Invoice Amt 2", "Invoice Desc 3", "Invoice Amt 3", "Invoice Desc 4", "Invoice Amt 4", "Invoice Desc 5", "Invoice Amt 5", "Maximum Aberrant Amount Allowed", "Amount Aberrant", "Ce Claim No", "Tracking ID", "Diagnosis Code", "Rx Number", "Fill Date", "Brand Name", "NDC", "Days Supply", "Refill Ind", "Claims", "Units", "Calculated Unit Price", "Calculated Sales Amt", "Calculated Rebate % of Sales", "Calculated Rebate Amt", "Total Exclusions"}, "Attribute", "Value"),
  #"Removed columns" = Table.RemoveColumns(#"Unpivoted columns", {"Value"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"Attribute", "Dispute Type"}, {"Benefit Stage Qualifier ", "Benefit Stage Qualifier"}})
in
  #"Renamed columns"