#!/bin/bash
# Script to clean up SeeHealth-specific files for public repository
# Generated: November 6, 2025
#
# IMPORTANT: This script removes sensitive files. 
# Make sure you have a backup before running!

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SENSITIVE_FILES_LIST="$REPO_ROOT/sensitive-files-list.txt"
DRY_RUN=true

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "======================================"
echo "Public Repository Cleanup Script"
echo "======================================"
echo ""

# Check if sensitive files list exists
if [ ! -f "$SENSITIVE_FILES_LIST" ]; then
    echo -e "${RED}ERROR: sensitive-files-list.txt not found!${NC}"
    echo "Run ./scripts/identify-sensitive-files.sh first"
    exit 1
fi

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --execute)
            DRY_RUN=false
            shift
            ;;
        --help)
            echo "Usage: $0 [--execute]"
            echo ""
            echo "Options:"
            echo "  --execute    Actually delete files (default is dry-run)"
            echo "  --help       Show this help message"
            echo ""
            echo "By default, this script runs in DRY-RUN mode and only shows"
            echo "what would be deleted. Use --execute to actually remove files."
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}⚠️  DRY-RUN MODE${NC}"
    echo "No files will be deleted. Run with --execute to actually clean up."
    echo ""
else
    echo -e "${RED}⚠️  EXECUTE MODE - FILES WILL BE DELETED!${NC}"
    echo ""
    echo -e "${YELLOW}This will permanently delete sensitive files.${NC}"
    echo "Make sure you have a backup!"
    echo ""
    read -p "Are you sure you want to continue? (type 'yes' to confirm): " confirm
    if [ "$confirm" != "yes" ]; then
        echo "Aborted."
        exit 0
    fi
    echo ""
fi

# Summary counters
deleted_count=0
failed_count=0
skipped_count=0

# Function to check if a file/directory can be regenerated
can_regenerate() {
    local path="$1"
    
    # Files that CAN be regenerated
    if [[ "$path" =~ ^data/column_mappings/ ]]; then
        echo "✓ Auto-generated by column_mapper.py"
        return 0
    fi
    
    if [[ "$path" =~ ^outputs/ ]]; then
        echo "✓ Generated by process_all_vendors.py"
        return 0
    fi
    
    if [[ "$path" =~ \.log$ ]] || [[ "$path" =~ \.pid$ ]]; then
        echo "✓ Runtime logs (regenerated on run)"
        return 0
    fi
    
    if [[ "$path" =~ frontend/dist ]] || [[ "$path" =~ frontend/node_modules ]]; then
        echo "✓ Build artifacts (npm run build / npm install)"
        return 0
    fi
    
    if [[ "$path" =~ __pycache__ ]] || [[ "$path" =~ \.pyc$ ]]; then
        echo "✓ Python cache (auto-generated)"
        return 0
    fi
    
    if [[ "$path" =~ \.venv ]]; then
        echo "✓ Virtual environment (pip install -r requirements.txt)"
        return 0
    fi
    
    if [[ "$path" =~ \.DS_Store ]] || [[ "$path" =~ ^tmp\. ]]; then
        echo "✓ Temporary system files"
        return 0
    fi
    
    # Files that CANNOT be easily regenerated
    if [[ "$path" =~ ^data/.*\.(csv|xlsx)$ ]]; then
        echo "⚠️  ORIGINAL DATA - Cannot regenerate"
        return 1
    fi
    
    if [[ "$path" =~ data/reference/ ]]; then
        echo "⚠️  REFERENCE DATA - Cannot regenerate"
        return 1
    fi
    
    if [[ "$path" =~ \.env$ ]]; then
        echo "⚠️  Configuration file - Manual setup required"
        return 1
    fi
    
    # Unknown files - be cautious
    echo "? Unknown file type"
    return 1
}

echo "======================================"
echo "Pre-Flight Check: File Regenerability"
echo "======================================"
echo ""

# Category 1: Files that can be safely deleted (regenerable)
echo -e "${GREEN}SAFE TO DELETE (Can be regenerated):${NC}"
echo ""

safe_patterns=(
    "data/column_mappings/*.json"
    "outputs/*"
    "scripts/logs/*"
    "frontend/dist"
    "frontend/node_modules"
    "frontend/.env"
    ".venv"
    "__pycache__"
    "*.pyc"
    ".pytest_cache"
    "*.log"
    "*.pid"
    ".DS_Store"
    "tmp.*"
)

for pattern in "${safe_patterns[@]}"; do
    echo "  ✓ $pattern"
done

echo ""
echo -e "${RED}CANNOT REGENERATE (Need to be preserved or replaced):${NC}"
echo ""

irreplaceable_patterns=(
    "data/*.csv"
    "data/*.xlsx"
    "data/reference/*.xlsx"
    ".env"
    ".env.local"
)

for pattern in "${irreplaceable_patterns[@]}"; do
    echo "  ⚠️  $pattern"
done

echo ""
echo "======================================"
echo "Cleanup Strategy"
echo "======================================"
echo ""
echo "1. DELETE: Auto-generated files (column mappings, outputs, logs)"
echo "2. DELETE: Build artifacts (node_modules, dist, .venv, cache)"
echo "3. KEEP: Original data files (will be .gitignored for public repo)"
echo "4. KEEP: .env.example (public template)"
echo "5. DELETE: .env (local secrets)"
echo ""

if [ "$DRY_RUN" = false ]; then
    read -p "Press Enter to continue with cleanup..."
fi

echo ""
echo "======================================"
echo "Starting Cleanup"
echo "======================================"
echo ""

# Category 1: Delete auto-generated column mappings
echo -e "${BLUE}[1/7] Cleaning column mappings...${NC}"
if [ -d "$REPO_ROOT/data/column_mappings" ]; then
    file_count=$(find "$REPO_ROOT/data/column_mappings" -type f | wc -l | tr -d ' ')
    echo "Found $file_count mapping files"
    
    if [ "$DRY_RUN" = false ]; then
        find "$REPO_ROOT/data/column_mappings" -type f -delete
        echo "  ✓ Deleted all column mapping files"
    else
        echo "  → Would delete all files in data/column_mappings/"
    fi
    ((deleted_count += file_count))
else
    echo "  Directory not found, skipping"
fi

# Category 2: Delete all outputs
echo ""
echo -e "${BLUE}[2/7] Cleaning classification outputs...${NC}"

# Backend outputs
if [ -d "$REPO_ROOT/outputs" ]; then
    file_count=$(find "$REPO_ROOT/outputs" -type f | wc -l | tr -d ' ')
    echo "Found $file_count output files"
    
    if [ "$DRY_RUN" = false ]; then
        find "$REPO_ROOT/outputs" -type f -delete
        # Keep the directory structure
        find "$REPO_ROOT/outputs" -type d -empty -delete 2>/dev/null || true
        mkdir -p "$REPO_ROOT/outputs"
        echo "  ✓ Deleted all output files"
    else
        echo "  → Would delete all files in outputs/"
    fi
    ((deleted_count += file_count))
else
    echo "  Directory not found, skipping"
fi

# Frontend copy of outputs
if [ -f "$REPO_ROOT/frontend/public/outputs/all_vendors_classification_results.csv" ]; then
    echo "Found frontend copy of classification results"
    
    if [ "$DRY_RUN" = false ]; then
        rm "$REPO_ROOT/frontend/public/outputs/all_vendors_classification_results.csv"
        echo "  ✓ Deleted frontend/public/outputs/all_vendors_classification_results.csv"
    else
        echo "  → Would delete frontend/public/outputs/all_vendors_classification_results.csv"
    fi
    ((deleted_count++))
fi

# Category 3: Delete logs
echo ""
echo -e "${BLUE}[3/7] Cleaning log files...${NC}"
log_count=0
if [ -d "$REPO_ROOT/scripts/logs" ]; then
    file_count=$(find "$REPO_ROOT/scripts/logs" -type f | wc -l | tr -d ' ')
    echo "Found $file_count log files"
    
    if [ "$DRY_RUN" = false ]; then
        rm -rf "$REPO_ROOT/scripts/logs"
        mkdir -p "$REPO_ROOT/scripts/logs"
        echo "  ✓ Deleted all log files"
    else
        echo "  → Would delete all files in scripts/logs/"
    fi
    ((deleted_count += file_count))
else
    echo "  No log directory found"
fi

# Category 4: Delete build artifacts
echo ""
echo -e "${BLUE}[4/7] Cleaning build artifacts...${NC}"

# Frontend dist
if [ -d "$REPO_ROOT/frontend/dist" ]; then
    echo "Found frontend/dist/"
    if [ "$DRY_RUN" = false ]; then
        rm -rf "$REPO_ROOT/frontend/dist"
        echo "  ✓ Deleted frontend/dist/"
    else
        echo "  → Would delete frontend/dist/"
    fi
    ((deleted_count++))
fi

# Frontend node_modules
if [ -d "$REPO_ROOT/frontend/node_modules" ]; then
    echo "Found frontend/node_modules/"
    if [ "$DRY_RUN" = false ]; then
        rm -rf "$REPO_ROOT/frontend/node_modules"
        echo "  ✓ Deleted frontend/node_modules/"
    else
        echo "  → Would delete frontend/node_modules/"
    fi
    ((deleted_count++))
fi

# Frontend .env
if [ -f "$REPO_ROOT/frontend/.env" ]; then
    echo "Found frontend/.env"
    if [ "$DRY_RUN" = false ]; then
        rm "$REPO_ROOT/frontend/.env"
        echo "  ✓ Deleted frontend/.env"
    else
        echo "  → Would delete frontend/.env"
    fi
    ((deleted_count++))
fi

# Category 5: Delete Python artifacts
echo ""
echo -e "${BLUE}[5/7] Cleaning Python artifacts...${NC}"

# .venv
if [ -d "$REPO_ROOT/.venv" ]; then
    echo "Found .venv/"
    if [ "$DRY_RUN" = false ]; then
        rm -rf "$REPO_ROOT/.venv"
        echo "  ✓ Deleted .venv/"
    else
        echo "  → Would delete .venv/"
    fi
    ((deleted_count++))
fi

# __pycache__ directories
pycache_count=$(find "$REPO_ROOT" -type d -name "__pycache__" 2>/dev/null | wc -l | tr -d ' ')
if [ "$pycache_count" -gt 0 ]; then
    echo "Found $pycache_count __pycache__ directories"
    if [ "$DRY_RUN" = false ]; then
        find "$REPO_ROOT" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
        echo "  ✓ Deleted all __pycache__ directories"
    else
        echo "  → Would delete all __pycache__ directories"
    fi
    ((deleted_count += pycache_count))
fi

# Category 6: Delete temporary files
echo ""
echo -e "${BLUE}[6/7] Cleaning temporary files...${NC}"

# .DS_Store files
ds_count=$(find "$REPO_ROOT" -name ".DS_Store" 2>/dev/null | wc -l | tr -d ' ')
if [ "$ds_count" -gt 0 ]; then
    echo "Found $ds_count .DS_Store files"
    if [ "$DRY_RUN" = false ]; then
        find "$REPO_ROOT" -name ".DS_Store" -delete
        echo "  ✓ Deleted all .DS_Store files"
    else
        echo "  → Would delete all .DS_Store files"
    fi
    ((deleted_count += ds_count))
fi

# tmp files
tmp_count=$(find "$REPO_ROOT" -maxdepth 1 -name "tmp.*" 2>/dev/null | wc -l | tr -d ' ')
if [ "$tmp_count" -gt 0 ]; then
    echo "Found $tmp_count tmp.* files"
    if [ "$DRY_RUN" = false ]; then
        find "$REPO_ROOT" -maxdepth 1 -name "tmp.*" -delete
        echo "  ✓ Deleted all tmp.* files"
    else
        echo "  → Would delete all tmp.* files"
    fi
    ((deleted_count += tmp_count))
fi

# Category 7: Delete local .env (keep .env.example)
echo ""
echo -e "${BLUE}[7/7] Cleaning environment files...${NC}"

if [ -f "$REPO_ROOT/.env" ]; then
    echo "Found .env (local secrets)"
    if [ "$DRY_RUN" = false ]; then
        rm "$REPO_ROOT/.env"
        echo "  ✓ Deleted .env"
    else
        echo "  → Would delete .env"
    fi
    ((deleted_count++))
fi

if [ -f "$REPO_ROOT/.env.local" ]; then
    echo "Found .env.local"
    if [ "$DRY_RUN" = false ]; then
        rm "$REPO_ROOT/.env.local"
        echo "  ✓ Deleted .env.local"
    else
        echo "  → Would delete .env.local"
    fi
    ((deleted_count++))
fi

echo ""
echo "======================================"
echo "Cleanup Summary"
echo "======================================"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}DRY-RUN MODE:${NC} No files were actually deleted"
    echo ""
    echo "Files/directories that would be removed: $deleted_count"
    echo ""
    echo "To actually clean up, run:"
    echo "  ./scripts/cleanup-for-public.sh --execute"
else
    echo -e "${GREEN}✓ Cleanup complete!${NC}"
    echo ""
    echo "Files/directories removed: $deleted_count"
fi

echo ""
echo "======================================"
echo "Files NOT Removed (Manual Action Required)"
echo "======================================"
echo ""
echo -e "${YELLOW}The following files contain sensitive data and must be${NC}"
echo -e "${YELLOW}handled manually before publishing to public repo:${NC}"
echo ""
echo "  1. data/Masked_Invoice_Claims_Extract.csv"
echo "  2. data/Masked_Invoice_Claims_Extract.xlsx"
echo "  3. data/Masked_Scrub_File_15.xlsx"
echo "  4. data/reference/Pharma_Crosswalk.xlsx"
echo "  5. data/reference/Exclusion Reason Codes.xlsx"
echo "  6. copilot-instrcutions-summary.md"
echo ""
echo -e "${BLUE}Options:${NC}"
echo "  A) Add these to .gitignore and don't publish them"
echo "  B) Replace with sanitized sample data"
echo "  C) Document as 'user must provide their own data'"
echo ""
echo "======================================"
echo "Next Steps"
echo "======================================"
echo ""
echo "1. Review remaining files for sensitive content"
echo "2. Update .gitignore for public repo (see sensitive-files-list.txt)"
echo "3. Create sanitized sample data if needed"
echo "4. Test that the application still works:"
echo ""
echo "   # Step 1: Backend setup"
echo "   python -m venv .venv"
echo "   source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate"
echo "   pip install -r requirements.txt"
echo ""
echo "   # Step 2: Configure environment"
echo "   cp .env.example .env"
echo "   # Edit .env with your Azure OpenAI credentials"
echo ""
echo "   # Step 3: Generate classification results (REQUIRED)"
echo "   python process_all_vendors.py"
echo ""
echo "   # Step 4: Frontend setup (in same terminal with venv active)"
echo "   cd frontend && npm install && cd .."
echo ""
echo "   # Step 5: Start services (in same terminal with venv active)"
echo "   ./scripts/run-services.sh"
echo ""
echo "   Note: Keep the virtual environment activated in your terminal!"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo -e "${GREEN}Ready to execute? Run with --execute flag${NC}"
fi

echo ""
