let
  Source = Excel.Workbook(Web.Contents("https://YOURSHAREPOINT.sharepoint.com/personal/YOURACCOUNT/Documents/Apps/Microsoft Power Query/Uploaded Files/Masked_Scrub_File_15 4.xlsx"), null, true),
  #"Navigation 1" = Source{[Item = "Hvsq Tkrbcgf", Kind = "Sheet"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column9", type text}, {"Column10", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column25", type text}, {"Column27", type text}, {"Column29", type text}, {"Column31", type text}, {"Column33", type text}, {"Column35", type text}, {"Column36", type text}, {"Column41", type text}, {"Column42", type text}, {"Column44", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column56", type text}, {"Column57", type text}, {"Column64", type text}, {"Column65", type text}, {"Column66", type text}, {"Column67", type text}, {"Column69", type text}, {"Column70", type text}, {"Column71", type text}}),
  #"Removed top rows" = Table.Skip(#"Changed column type", 2),
  #"Promoted headers" = Table.PromoteHeaders(#"Removed top rows", [PromoteAllScalars = true]),
  #"Renamed columns" = Table.RenameColumns(#"Promoted headers", {{"Benefit Stage Qualifier ", "Benefit Stage Qualifier"}}),
  #"Unpivoted only selected columns" = Table.Unpivot(#"Renamed columns", {"TIMEFRAME - PRODUCT", "TIMEFRAME - PRIOR PERIOD CLAIMS", "RX NUMBER - NON-STANDARD", "RX NUMBER - CUSTOM 340B", "PRODUCT - NON-CONTRACT NDC", "PRIOR EXCLUSION CREDIT", "PHARMACY - NON-STANDARD", "PHARMACY - INACTIVE", "PHARMACY - CUSTOM UP FRONT", "PHARMACY - CUSTOM HOSPITAL", "PHARMACY - CUSTOM FSS", "PHARMACY - CUSTOM 340B", "FORMULARY NON-COMPLIANCE POLICY", "FORMULARY NON-COMPLIANCE", "DUPLICATION - MEDICAID - HORIZONTAL/VERTICAL", "DUPLICATION - HORIZONTAL/VERTICAL", "CUSTOM 340B CP1", "CUSTOM 340B COVERED ENTITY", "ABERRANT QUANTITY - NON-MAIL", "ABERRANT QUANTITY - MAIL"}, "Attribute", "Value"),
  #"Renamed columns 1" = Table.RenameColumns(#"Unpivoted only selected columns", {{"Attribute", "Dispute Desc"}})
in
  #"Renamed columns 1"