let
  Source = Table.NestedJoin(#"Get Hvsq Tkrbcgf", {"Dispute Desc"}, #"Get Reason Lookup Master", {"hvsq key"}, "Version 2 - Get Reason Lookup Master", JoinKind.Inner),
  #"Expanded Version 2 - Get Reason Lookup Master 1" = Table.ExpandTableColumn(Source, "Version 2 - Get Reason Lookup Master", {"CodeID", "Reason Code", "Description", "Comment", "Rank"}, {"CodeID", "Reason Code", "Description", "Comment", "Rank"}),
  #"Merged queries" = Table.NestedJoin(#"Expanded Version 2 - Get Reason Lookup Master 1", {"Ce Claim No", "Rank", "CodeID"}, #"Find Top Priority Dispute", {"Ce Claim No", "Top Priority", "Top Code"}, "Version 2b - Find Top Priority Dispute", JoinKind.Inner),
  #"Removed columns" = Table.RemoveColumns(#"Merged queries", {"Client Name", "Client ID", "Client Type", "Std Mail Indicator", "Bid Enhancement ID", "Client Class Code", "Rebate Transaction ID", "Benefit Stage Qualifier", "Segment 1", "Rebate Batch Number", "File Name Text", "Version 2b - Find Top Priority Dispute", "Refill Ind", "Claims", "Units", "Calculated Unit Price", "Calculated Sales Amt", "Calculated Rebate % of Sales", "Calculated Rebate Amt", "Invoice Desc 4", "Invoice Amt 4", "Invoice Desc 5", "Invoice Amt 5", "Maximum Aberrant Amount Allowed", "Amount Aberrant"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {{"Provider XRef ID", type text}, {"NCPDP ID", type text}, {"NPI", type text}, {"Paid Amt", type number}, {"CoPay Amt", type number}, {"Invoiced Rebate Rate", type number}, {"Invoiced Rebate Amt", type number}, {"Invoice Amt 1", type number}, {"Invoice Amt 2", type number}, {"Invoice Amt 3", type number}, {"Ce Claim No", type text}, {"Tracking ID", type text}, {"Rx Number", type text}, {"Fill Date", type date}, {"Days Supply", Int64.Type}, {"Total Exclusions", Int64.Type}, {"Value", Int64.Type}, {"CodeID", Int64.Type}, {"Reason Code", type text}})
in
  #"Changed column type"