let
  Source = Table.NestedJoin(#"Get GpkDke", {"Dispute Type"}, #"Get Reason Lookup Master", {"gpkdke key"}, "Get Reason Lookup Master", JoinKind.Inner),
  #"Expanded Get Reason Lookup Master" = Table.ExpandTableColumn(Source, "Get Reason Lookup Master", {"CodeID", "Reason Code", "Description", "Comment", "Rank"}, {"CodeID", "Reason Code", "Description", "Comment", "Rank"}),
  #"Merged queries" = Table.NestedJoin(#"Expanded Get Reason Lookup Master", {"Ce Claim No", "Rank", "CodeID"}, #"Find Top Priority and Code", {"Ce Claim No", "Top Priority", "Top Code"}, "Find Top Priority and Code", JoinKind.Inner),
  #"Changed column type" = Table.TransformColumnTypes(#"Merged queries", {{"Client Name", type text}, {"Client ID", type text}, {"Client Type", type text}, {"Provider Name", type text}, {"Provider State", type text}, {"Provider XRef ID", type text}, {"NCPDP ID", type text}, {"NPI", type text}, {"Provider Type", type text}, {"Std Mail Indicator", type text}, {"Paid Amt", type number}, {"CoPay Amt", type number}, {"Bid Enhancement ID", type text}, {"Client Class Code", type text}, {"Plan Name", type text}, {"Rebate Transaction ID", type text}, {"Benefit Stage Qualifier", type text}, {"Segment 1", type text}, {"Rebate Batch Number", type text}, {"File Name Text", type text}, {"Payout Cell Number", type text}, {"Formulary Code", type text}, {"Invoiced Rebate Rate", type number}, {"Invoiced Rebate Amt", type number}, {"Invoice Desc 1", type text}, {"Invoice Amt 1", type number}, {"Invoice Desc 2", type text}, {"Invoice Amt 2", type number}, {"Invoice Desc 3", type text}, {"Invoice Amt 3", type number}, {"Invoice Desc 4", type text}, {"Invoice Amt 4", type number}, {"Invoice Desc 5", type text}, {"Invoice Amt 5", type number}, {"Maximum Aberrant Amount Allowed", type number}, {"Amount Aberrant", type number}, {"Ce Claim No", type text}, {"Tracking ID", type text}, {"Diagnosis Code", type text}, {"Rx Number", type text}, {"Fill Date", type date}, {"Brand Name", type text}, {"NDC", type text}, {"Days Supply", Int64.Type}, {"Refill Ind", Int64.Type}, {"Claims", Int64.Type}, {"Units", Int64.Type}, {"Calculated Unit Price", type number}, {"Calculated Sales Amt", type text}, {"Calculated Rebate % of Sales", type number}, {"Calculated Rebate Amt", type number}, {"CodeID", type text}, {"Reason Code", type text}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Find Top Priority and Code"})
in
  #"Removed columns"